---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paddock.dev
  resources:
  - auditevents
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - paddock.dev
  resources:
  - clusterharnesstemplates
  - harnesstemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paddock.dev
  resources:
  - harnessruns
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paddock.dev
  resources:
  - harnessruns/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - paddock.dev
  resources:
  - harnessruns/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
