#!/usr/bin/env bash
#
# gen-helm-chart.sh — render kustomize output into the Helm chart
# under charts/paddock/. Splits CustomResourceDefinitions into
# charts/paddock/crds/ (Helm installs these once) and routes
# everything else into templates/paddock.yaml with Helm value
# substitutions for the manager image and optional collector-image
# flag.
#
# Run this whenever config/** changes. The generated files are
# committed so `helm install` works straight from a fresh clone
# without needing kustomize locally.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
KUSTOMIZE="${ROOT}/bin/kustomize"
CHART_DIR="${ROOT}/charts/paddock"
CRDS_DIR="${CHART_DIR}/crds"
TEMPLATES_DIR="${CHART_DIR}/templates"
OUT_TEMPLATE="${TEMPLATES_DIR}/paddock.yaml"

if [[ ! -x "$KUSTOMIZE" ]]; then
  echo "kustomize not found at $KUSTOMIZE — run 'make kustomize' first" >&2
  exit 1
fi

mkdir -p "$CRDS_DIR" "$TEMPLATES_DIR"
rm -f "$CRDS_DIR"/*.yaml "$OUT_TEMPLATE"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Render the full kustomize output, then split into individual docs.
"$KUSTOMIZE" build "${ROOT}/config/default" >"$tmp/all.yaml"

# Use yq if present (cleaner split); fall back to awk otherwise.
if command -v yq >/dev/null 2>&1; then
  yq -s '"'"$tmp"'/doc-" + ($index|tostring)' "$tmp/all.yaml" >/dev/null
else
  awk 'BEGIN{n=0; f=""} /^---$/ {n++; f="'"$tmp"'/doc-" n ".yml"; next} {if (f=="") {n=0; f="'"$tmp"'/doc-0.yml"} print > f}' "$tmp/all.yaml"
fi

header='# Generated by hack/gen-helm-chart.sh from config/default. Do not edit.'
echo "$header" >"$OUT_TEMPLATE"

for doc in "$tmp"/doc-*.yml "$tmp"/doc-*.yaml; do
  [[ -f "$doc" ]] || continue
  [[ -s "$doc" ]] || continue

  kind=$(awk '/^kind:/ {print $2; exit}' "$doc")
  name=$(awk '/^  name:/ {print $2; exit}' "$doc")

  case "$kind" in
    CustomResourceDefinition)
      # CRDs live outside templates/ — Helm installs them once and
      # does not upgrade in place. Safer for a schema surface that
      # should evolve deliberately.
      cp "$doc" "${CRDS_DIR}/${name}.yaml"
      ;;
    Namespace)
      # Namespace is created by Helm's --create-namespace flag or
      # pre-existing. Skip to keep the chart idempotent.
      ;;
    "")
      ;;
    *)
      echo "---" >>"$OUT_TEMPLATE"
      # Substitute the manager image with Helm values. The rendered
      # value is literal "paddock-manager:dev"; preserve the
      # tag-defaulting semantics via .Chart.AppVersion.
      # Use '@' as the sed delimiter because the Helm template syntax
      # {{ tag | default … }} contains a bare pipe character.
      #
      # Three substitutions get rewritten:
      #   - the manager container image (Deployment.spec.containers[0].image)
      #   - the --collector-image arg on the manager, which the
      #     controller forwards into every HarnessRun Pod's collector
      #     sidecar
      #   - the --recent-events-cap arg, wired from .Values.recentEventsCap
      #     (ADR-0007)
      sed \
        -e 's@image: paddock-manager:dev@image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}@g' \
        -e 's@- --collector-image=paddock-collector:dev@- --collector-image={{ .Values.collectorImage.repository }}:{{ .Values.collectorImage.tag | default .Chart.AppVersion }}@g' \
        -e 's@- --recent-events-cap=50@- --recent-events-cap={{ .Values.recentEventsCap | default 50 }}@g' \
        -e 's@- --audit-retention-days=30@- --audit-retention-days={{ .Values.auditRetentionDays | default 30 }}@g' \
        -e 's@image: paddock-broker:dev@image: {{ .Values.brokerImage.repository }}:{{ .Values.brokerImage.tag | default .Chart.AppVersion }}@g' \
        -e 's@- --proxy-image=paddock-proxy:dev@- --proxy-image={{ if .Values.proxyImage.repository }}{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag | default .Chart.AppVersion }}{{ end }}@g' \
        -e 's@- --proxy-allow=$@- --proxy-allow={{ .Values.proxyAllowList | default "" }}@g' \
        -e 's@- --iptables-init-image=paddock-iptables-init:dev@- --iptables-init-image={{ if .Values.iptablesInitImage.repository }}{{ .Values.iptablesInitImage.repository }}:{{ .Values.iptablesInitImage.tag | default .Chart.AppVersion }}{{ end }}@g' \
        -e 's@- --home-init-image=$@- --home-init-image={{ .Values.homeInitImage | default "" }}@g' \
        -e 's@- --networkpolicy-enforce=auto@- --networkpolicy-enforce={{ .Values.proxy.networkPolicy.enforce | default "auto" }}@g' \
        "$doc" >>"$OUT_TEMPLATE"
      ;;
  esac
done

echo "chart files written:"
echo "  ${CHART_DIR}/Chart.yaml (static)"
echo "  ${CHART_DIR}/values.yaml (static)"
echo "  ${OUT_TEMPLATE}"
ls "${CRDS_DIR}" | sed 's|^|  '"${CRDS_DIR}"/'|'
