## Append samples of your project ##
resources:
- paddock_v1alpha1_harnesstemplate.yaml
- paddock_v1alpha1_clusterharnesstemplate.yaml
- paddock_v1alpha1_harnessrun.yaml
- paddock_v1alpha1_workspace.yaml
- paddock_v1alpha1_brokerpolicy.yaml
- paddock_v1alpha1_brokerpolicy_static.yaml
- paddock_v1alpha1_auditevent.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
