apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker
  namespace: system
  labels:
    app.kubernetes.io/name: paddock
    app.kubernetes.io/component: broker
    app.kubernetes.io/managed-by: kustomize
